#!/bin/bash

# 1. Gerekli Python paketlerini yükleme
pip install github3 pyperclip tkinter ttk

# 2. ~/github dizinini oluşturma
mkdir -p ~/github

# 3. Repo'yu indirme
git clone https://github.com/OmerFaruk-Celik/Python_OTO_COMMIT.git ~/github/Python_OTO_COMMIT

# 4. repo.py dosyasını /usr/bin/repo'ya kopyalama
sudo cp ~/github/Python_OTO_COMMIT/repo.py /usr/bin/repo

# 5. Crontab'a komut ekleme
echo "* * * * * /usr/bin/python3 ~/github/Python_OTO_COMMIT/kontrol.py > ~/github/Python_OTO_COMMIT/output.log 2>&1" | sudo tee -a /etc/crontab

echo "INSTALL işlemi tamamlandı!"
