#!/bin/bash

# Script'in yürütülebilir olmasını sağla
chmod +x "$0"
sudo git config --system core.longpaths true
sudo git config --global core.protectNTFS false
sudo apt-get install python3-tk
sudo apt-get install xclip xselect

# 1. Gerekli Python paketlerini yükleme
echo "Gerekli Python paketlerini indiriyorum..."
pip install github3.py pyperclip tk
pip3 install PyGithub

# 2. ~/github/MAIN dizinini oluşturma
echo "~/github/MAIN dizinini oluşturuyorum..."
mkdir -p ~/github/MAIN

echo "repo.py dosyasını /usr/bin/repo dizininden siliyorum"
sudo rm -rf /usr/bin/repo

echo "Python_OTO_COMMIT dosyasını ~/github/MAIN/Python_OTO_COMMIT/ dizininden siliyorum"
sudo rm -rf ~/github/MAIN/Python_OTO_COMMIT/


# 3. Repo'yu indirme
echo "Repo'yu indiriyorum..."
git clone https://github.com/OmerFaruk-Celik/Python_OTO_COMMIT.git ~/github/MAIN/Python_OTO_COMMIT/

# 4. repo.py dosyasını /usr/bin/repo'ya kopyalama


echo "repo.py dosyasını kopyalıyorum..."
sudo cp ~/github/MAIN/Python_OTO_COMMIT/repo.py /usr/bin/repo

# 5. Crontab'a komut ekleme

echo "Eski Crontab içeriklerini siliyorum."
crontab -l > crontab.txt
sed '/^\* \* \* \* \* \/usr\/bin\/python3 ~\/github\/MAIN\/Python_OTO_COMMIT\/kontrol.py > ~.*$/d' crontab.txt > new_crontab.txt
cat new_crontab.txt > crontab.txt

sed '/^\* \* \* \* \* \/usr\/bin\/python3 ~\/github\/Python_OTO_COMMIT\/kontrol.py > ~.*$/d' crontab.txt > new_crontab.txt
cat new_crontab.txt > crontab.txt

sed '/^\* \* \* \* \* \/usr\/bin\/python3 ~\/github\/Python_OTO_COMMIT\/kontrol.py > ~.*$/d' crontab.txt > new_crontab.txt
cat new_crontab.txt > crontab.txt

sed '/^\* \* \* \* \* \/usr\/bin\/python3.*$/d' crontab.txt > new_crontab.txt
cat new_crontab.txt > crontab.txt
 
crontab crontab.txt



echo "Crontab'a komut ekliyorum..."
(crontab -l 2>/dev/null; echo "* * * * * /usr/bin/python3 ~/github/MAIN/Python_OTO_COMMIT/kontrol.py > ~/github/MAIN/Python_OTO_COMMIT/output.log 2>&1") | crontab -

# 6. Bilgiler.txt dosyasını düzenleme
echo "bilgiler.txt dosyasını düzenleyin..."
echo "Kullanıcı Adı,E-Posta,GITHUB_TOKEN" > ~/github/MAIN/bilgiler.txt
echo "Lütfen bilgiler.txt dosyasını düzenleyin ve bilgilerinizi ekleyin."
echo "Token'ı GitHub'dan oluşturun."
echo "Daha sonra script'i çalıştırın."

#cd ..
#rm -rf ./Python_OTO_COMMIT
echo "INSTALL işlemi tamamlandı! terminale repo yazarak kullanıcı arayüzüne ulaşabilirsiniz."
repo
